routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::get('/admin', 'AdminController@index');
    Route::resource('users','UserController');
    Route::resource('acadamic', 'AcadamicYearController');
    Route::resource('projecttype', 'ProjectTypeController');

    Route::get('student_index','UserController@student_index')->name('users.student_index');
    Route::get('create_student','UserController@create_student')->name('users.create_student');
    Route::post('create_student','UserController@store_student')->name('users.store_student');
    Route::get('edit_student/{id}','UserController@edit_student')->name('users.edit_student');
    Route::post('edit_student/{id}','UserController@update_student')->name('users.update_student');
    Route::delete('destroy_student/{id}','UserController@destroy_student')->name('users.destroy_student');

    Route::get('supervisor_index','UserController@supervisor_index')->name('users.supervisor_index');
    Route::get('create_supervisor','UserController@create_supervisor')->name('users.create_supervisor');
    Route::post('create_supervisor','UserController@store_supervisor')->name('users.store_supervisor');
    Route::get('edit_supervisor/{id}','UserController@edit_supervisor')->name('users.edit_supervisor');
    Route::post('edit_supervisor/{id}','UserController@update_supervisor')->name('users.update_supervisor');
    Route::get('supervisor_role/{id}','UserController@supervisor_role')->name('users.supervisor_role');
    Route::patch('update_supervisor_role/{id}','UserController@update_supervisor_role')->name('users.update_supervisor_role');
    Route::delete('destroy_supervisor/{id}','UserController@destroy_supervisor')->name('users.destroy_supervisor');

    Route::get('coordinator_index','UserController@coordinator_index')->name('users.coordinator_index');
    Route::get('create_coordinator','UserController@create_coordinator')->name('users.create_coordinator');
    Route::post('create_coordinator','UserController@store_coordinator')->name('users.store_coordinator');
    Route::get('edit_coordinator/{id}','UserController@edit_coordinator')->name('users.edit_coordinator');
    Route::post('edit_coordinator/{id}','UserController@update_coordinator')->name('users.update_coordinator');
    Route::get('coordinator_role/{id}','UserController@coordinator_role')->name('users.coordinator_role');
    Route::patch('update_coordinator_role{id}','UserController@update_coordinator_role')->name('users.update_coordinator_role');
    Route::delete('destroy_coordinator/{id}','UserController@destroy_coordinator')->name('users.destroy_coordinator');

    Route::get('change-password', 'AdminController@changepassword')->name('password_change');
    Route::post('change-password', 'AdminController@store')->name('change.password');

    Route::get('student/changepassword', 'StudentController@changestudentpassword')->name('student.change_password');
    Route::post('student/changepassword', 'StudentController@storestudentpassword')->name('change.student.password');

    Route::get('supervisor/updatepassword', 'SupervisorController@changesupervisorpassword')->name('supervisor.password');
    Route::post('supervisor/updatepassword', 'SupervisorController@storesupervisorpassword')->name('supervisor.change_password');

    Route::get('coordinator/passwordchange', 'CoordinatorController@changecoordinatorpassword')->name('coordinator.passwordchange');
    Route::post('coordinator/passwordchange', 'CoordinatorController@storecoordinatorpassword')->name('coordinator.changepassword');

});

Route::get('/student', 'StudentController@index')->name('student.index')->middleware('student');

    

Route::get('profile', 'StudentController@profile')->name('student.profile');
Route::get('profile/edit_avatar/{id}', 'StudentController@edit_avatar')->name('profile.edit');
Route::post('profile/edit_avatar/{id}', 'StudentController@update_avatar')->name('profile.update');
Route::get('profile/edit_details/{id}', 'StudentController@edit_details')->name('profile.edit_details');
Route::post('profile/edit_details/{id}', 'StudentController@update_name')->name('profile.update_name');
Route::get('studentproject', 'StudentController@project')->name('all_project.index');

Route::get('project', 'ProjectController@index')->name('project.index');
Route::get('project/AddDetails','ProjectController@create_details')->name('project.create_details');
Route::post('project/AddDetails','ProjectController@store_details')->name('project.store_details');
Route::get('project/edit_details/{id}', 'ProjectController@edit_details')->name('project.edit_details');
Route::post('project/edit_details/{id}', 'ProjectController@update_details')->name('project.update_details');

Route::get('project/AddDocument','ProjectController@create_document')->name('project.create');
Route::post('project/AddDocument','ProjectController@store_document')->name('project.store');
Route::get('project/edit/{id}', 'ProjectController@edit')->name('project.edit');
Route::post('project/edit/{id}', 'ProjectController@update')->name('project.update');
Route::get('viewpdf/{id}','ProjectController@view')->name('pdf.view');


Route::get('/supervisor', 'SupervisorController@index')->name('supervisor.index')->middleware('supervisor');
Route::get('supervisor/projects','SupervisorController@project')->name('supervisor.project')->middleware('supervisor');
Route::get('/project/showproject/{id}','SupervisorController@show_project')->name('projects.show_project');
Route::get('viewpdf/{id}','SupervisorController@view')->name('pdf.view');


Route::get('/coordinator', 'CoordinatorController@index')->name('coordinator.index')->middleware('coordinator');
Route::get('/projects','CoordinatorController@project')->name('coordinator.project');
Route::get('/projects/show/{id}','CoordinatorController@show')->name('projects.show');
Route::get('viewpdf/{id}','CoordinatorController@view')->name('pdf.view');
Route::get('/allprojects','CoordinatorController@all_project')->name('coordinator.all_project');
Route::get('/projects/show/{id}','CoordinatorController@show_project')->name('projects.show_all');

resources/views/backend/acadamic/create.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mini Handler | Admin</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/font-awesome/css/font-awesome.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/Ionicons/css/ionicons.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/plugins/iCheck/all.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/plugins/timepicker/bootstrap-timepicker.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/select2/dist/css/select2.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/dist/css/AdminLTE.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/dist/css/skins/_all-skins.min.css')}}">

  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        @toastr_css
</head>
<body class="hold-transition skin-blue fixed sidebar-mini">
<div class="wrapper">

<header class="main-header">
    <a href="index2.html" class="logo">
      <span class="logo-lg"><b>Mini</b> Handler</span>
    </a>

    <nav class="navbar navbar-static-top">

      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">


          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{asset('admin_dashboard/dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ Auth::user()->username }}</span>
            </a>
            <ul class="dropdown-menu">

              <li class="user-header">
                <img src="{{asset('admin_dashboard/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">

                <p>
                {{ Auth::user()->username }} - {{ Auth::user()->role }}
                  <small>Member since {{ Auth::user()->created_at }}</small>
                </p>
              </li>

              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">{{ __('Sign out') }}</a>
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
              </form>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
</header>

  <aside class="main-sidebar">

    <section class="sidebar">

      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{asset('admin_dashboard/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{Auth::user()->username}}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>

      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Top Menu</li>

        <li class="treeview">
        <a href="{{route('users.index')}}">
          <i class="fa fa-user"></i> <span>User Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{route('users.student_index')}}"><i class="fa fa-graduation-cap"></i> Student Management</a></li>
            <li><a href="{{route('users.supervisor_index')}}"><i class="fa fa-user"></i> Supervisor Management</a></li>
            <li><a href="{{route('users.coordinator_index')}}"><i class="fa fa-user"></i> Coordinator Management</a></li>
          </ul>
        </li>
        <li><a href="{{route('acadamic.index')}}"><i class="fa fa-book"></i> <span>Acadamic Year Management</span></a></li>
        <li><a href="{{route('projecttype.index')}}"><i class="fa fa-book"></i> <span>Project Type Management</span></a></li>
        <li><a href="{{route('password_change')}}"><i class="fa fa-key"></i> <span>Change Password</span></a></li>
      </ul>
    </section>
  </aside>

  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Acadamic Year Management
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">create Year</li>
      </ol>
    </section>

    <section class="content">

      <div class="row">

        <section class="col-lg-12  col-md-12 col-sm-12">

            <div class="box">
                <div class="box-primary">
                    <div class="box-footer clearfix no-border">
                        <a  href="{{route('acadamic.index')}}"><button type="button" class="btn btn-success pull-left"> Back</button></a>
                    </div>
                </div>
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                        </ul>
                    </div>
                @endif
                <form role="form" action="{{ route('acadamic.store') }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('POST') }}
                    <div class="box-body">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="acadamicyear">Year</label>
                                <input type="text" class="form-control @error('acadamicyear') is-invalid @enderror" value="{{ old('acadamicyear') }}" 
                                    required autocomplete="acadamicyear" id="acadamicyear" name="acadamicyear" placeholder="Enter the Year">
                            </div>
                        </div>
                    </div>

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </section>
      </div>

    </section>
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright <a>MINI Handler</a>.</strong> All rights
    reserved.
  </footer>
  @jquery
      @toastr_js
      @toastr_render
</div>

<script src="{{asset('admin_dashboard/bower_components/jquery/dist/jquery.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/select2/dist/js/select2.full.min.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/input-mask/jquery.inputmask.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/input-mask/jquery.inputmask.date.extensions.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/input-mask/jquery.inputmask.extensions.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/moment/min/moment.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/timepicker/bootstrap-timepicker.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/iCheck/icheck.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/fastclick/lib/fastclick.js')}}"></script>
<script src="{{asset('admin_dashboard/dist/js/adminlte.min.js')}}"></script>
<script src="{{asset('admin_dashboard/dist/js/demo.js')}}"></script>

</body>
</html>

resources/views/backend/acadamic/edit.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mini Handler | Admin</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/font-awesome/css/font-awesome.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/Ionicons/css/ionicons.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/plugins/iCheck/all.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/plugins/timepicker/bootstrap-timepicker.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/bower_components/select2/dist/css/select2.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/dist/css/AdminLTE.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin_dashboard/dist/css/skins/_all-skins.min.css')}}">

  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        @toastr_css
</head>
<body class="hold-transition skin-blue fixed sidebar-mini">
<div class="wrapper">

<header class="main-header">
    <a href="index2.html" class="logo">
      <span class="logo-lg"><b>Mini</b> Handler</span>
    </a>

    <nav class="navbar navbar-static-top">

      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">


          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{asset('admin_dashboard/dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ Auth::user()->username }}</span>
            </a>
            <ul class="dropdown-menu">

              <li class="user-header">
                <img src="{{asset('admin_dashboard/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">

                <p>
                {{ Auth::user()->username }} - {{ Auth::user()->role }}
                  <small>Member since {{ Auth::user()->created_at }}</small>
                </p>
              </li>

              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">{{ __('Sign out') }}</a>
                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
              </form>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
</header>

  <aside class="main-sidebar">

    <section class="sidebar">

      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{asset('admin_dashboard/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{Auth::user()->username}}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>

      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Top Menu</li>

        <li class="treeview">
        <a href="{{route('users.index')}}">
          <i class="fa fa-user"></i> <span>User Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{route('users.student_index')}}"><i class="fa fa-graduation-cap"></i> Student Management</a></li>
            <li><a href="{{route('users.supervisor_index')}}"><i class="fa fa-user"></i> Supervisor Management</a></li>
            <li><a href="{{route('users.coordinator_index')}}"><i class="fa fa-user"></i> Coordinator Management</a></li>
          </ul>
        </li>
        <li><a href="{{route('acadamic.index')}}"><i class="fa fa-book"></i> <span>Acadamic Year Management</span></a></li>
        <li><a href="{{route('projecttype.index')}}"><i class="fa fa-book"></i> <span>Project Type Management</span></a></li>
        <li><a href="{{route('password_change')}}"><i class="fa fa-key"></i> <span>Change Password</span></a></li>
      </ul>
    </section>
  </aside>

  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Edit Student's's Details
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Student</a></li>
        <li class="active">Edit Details</li>
      </ol>
    </section>

    <section class="content">

      <div class="box box-primary">
        <div class="box-footer clearfix no-border">
          <a  href="{{route('acadamic.index')}}"><button type="button" class="btn btn-success pull-left">Back</button></a>
        </div>

        @if (count($errors) > 0)
          <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
              <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
              </ul>
          </div>
        @endif

        
        {!! Form::model($acadamic, ['method' => 'PATCH','route' => ['acadamic.update', $acadamic->id]]) !!}
            <div class="box-body">
                <div class="row">
                    <div class="col-md-8">

                        <div class="form-group">
                        <label for="acadamicyear">User Name</label>
                        <input type="text" class="form-control" class="form-control @error('acadamicyear') is-invalid @enderror"
                                                name="acadamicyear" value="{{ $acadamic->acadamicyear }}" required autofocus>
                        </div>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
    {!! Form::close() !!}

      </div>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright <a>MINI Handler</a>.</strong> All rights
    reserved.
  </footer>
  @jquery
      @toastr_js
      @toastr_render
</div>

<script src="{{asset('admin_dashboard/bower_components/jquery/dist/jquery.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/select2/dist/js/select2.full.min.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/input-mask/jquery.inputmask.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/input-mask/jquery.inputmask.date.extensions.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/input-mask/jquery.inputmask.extensions.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/moment/min/moment.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/timepicker/bootstrap-timepicker.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<script src="{{asset('admin_dashboard/plugins/iCheck/icheck.min.js')}}"></script>
<script src="{{asset('admin_dashboard/bower_components/fastclick/lib/fastclick.js')}}"></script>
<script src="{{asset('admin_dashboard/dist/js/adminlte.min.js')}}"></script>
<script src="{{asset('admin_dashboard/dist/js/demo.js')}}"></script>

</body>
</html>

resources/views/backend/acadamic/index.blade.php
@extends('backend.admin.master')

@section('content')
  <div class="content-wrapper">

    <section class="content-header">
      <h1>
        Acadamic Year Management
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Acadamic Year Management</li>
      </ol>
    </section>

    <section class="content">

      <div class="row">

        <section class="col-lg-12  col-md-12 col-sm-12">

            <div class="box">
            <div class="box-primary">
              <div class="box-footer clearfix no-border">
              <a  href="{{route('acadamic.create')}}"><button type="button" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Add New Year</button></a>
              </div>
            </div>
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped table-hover">
                  <thead>
                  <tr>
                    <th>No.</th>
                    <th>Year</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                    @foreach ($data as $key => $acadamic)
                      <tr>
                        <td>{{ ++$i }}</td>
                        <td>{{ $acadamic->acadamicyear }}</td>
                        <td>
                          <a class="btn btn-primary" href="{{ route('acadamic.edit',$acadamic->id) }}">Edit</a>
                            {!! Form::open(['method' => 'DELETE','route' => ['acadamic.destroy', $acadamic->id],'style'=>'display:inline']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                            {!! Form::close() !!}
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
        </section>
      </div>

    </section>
  </div>
@endsection